### ISSUE TITLE
Decide on a keycap materials

### ISSUE THREAD

**Issue by Xenosb** [stankec/omgkbd#10]
Choose between 3D printing our own ABS or ordering from ebay/AliExpress.

**Comment by stankec** [comment]
I'm thinking about buying these https://www.massdrop.com/buy/tai-hao-aquatic-abs-doubleshot-keycap-set for my existing keyboard, so I'll have a spare set.

**Comment by Xenosb** [comment]
Do it. Add the item to the BoM.
