### ISSUE TITLE
3D print a test keycap

### ISSUE THREAD

**Issue by Xenosb** [stankec/omgkbd#12]
Try manufacturing a keycap with good enough ergonomics

**Comment by stankec** [comment]
This is my first attempt. I'll try to lower the layer height and try a few different things.
![img_0164](https://user-images.githubusercontent.com/1655218/31878809-90032b24-b7db-11e7-80ee-4c17b6c59934.JPG)
![img_0617](https://user-images.githubusercontent.com/1655218/31878872-d36b6cbe-b7db-11e7-94dd-fe30274740d7.JPG)

**Comment by stankec** [comment]
I think we have a winner.
The one on the bottom is printed with 0.6 layer height and 105% flowrate.
![img_9201](https://user-images.githubusercontent.com/1655218/31882830-5534a218-b7e8-11e7-8798-ccf5d82ed761.JPG)

**Comment by Xenosb** [comment]
So are we going to order keycaps or 3d print them?

**Comment by stankec** [comment]
I'll buy the ones mentioned in #10 and I'll produce a set of 3D printed ones then we can check if it works as expected.
I'd like for this repo to have everything to build your own keyboard - that includes keycaps, body, ...

**Comment by Xenosb** [comment]
Then I'll close this issue and add print keycaps and buy keycaps tasks.
