### ISSUE TITLE
Order keycaps

### ISSUE THREAD

**Issue by Xenosb** [stankec/omgkbd#15]
@stankec please order keycaps from massdrop
https://www.massdrop.com/buy/tai-hao-aquatic-abs-doubleshot-keycap-set

**Comment by Xenosb** [comment]
Add entry to BOM when done

**Comment by Xenosb** [comment]
@stankec have you ordered the keycaps?

**Comment by stankec** [comment]
Just now.

**Comment by Xenosb** [comment]
@stankec did you fill in the BoM?

**Comment by stankec** [comment]
Did it just now
